export const codeToCountryNames: Record<string, string> = {
  IN: 'India',
  US: 'United States',
  NZ: 'New Zealand',
  CN: 'China',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  NP: 'Nepal',
  BT: 'Bhutan',
  MM: 'Myanmar',
  AF: 'Afghanistan',
  CA: 'Canada',
  MX: 'Mexico',
  AU: 'Australia',
  GB: 'United Kingdom',
  FR: 'France',
  DE: 'Germany',
  IT: 'Italy',
  ES: 'Spain',
  PT: 'Portugal',
  BE: 'Belgium',
  NL: 'Netherlands',
  CH: 'Switzerland',
  AT: 'Austria',
  PL: 'Poland',
  CZ: 'Czech Republic',
  BR: 'Brazil',
  AR: 'Argentina',
  UY: 'Uruguay',
  PY: 'Paraguay',
  BO: 'Bolivia',
  PE: 'Peru',
  CL: 'Chile',
  CO: 'Colombia',
  VE: 'Venezuela',
  GY: 'Guyana',
  SR: 'Suriname',
  JP: 'Japan',
  KR: 'South Korea',
  TH: 'Thailand',
  LA: 'Laos',
  KH: 'Cambodia',
  VN: 'Vietnam',
  MY: 'Malaysia',
  SG: 'Singapore',
  ID: 'Indonesia',
  RU: 'Russia',
  NO: 'Norway',
  SE: 'Sweden',
  FI: 'Finland',
  EE: 'Estonia',
  LV: 'Latvia',
  LT: 'Lithuania',
  BY: 'Belarus',
  UA: 'Ukraine',
  GE: 'Georgia',
  AZ: 'Azerbaijan',
  TR: 'Turkey',
  IR: 'Iran',
  IQ: 'Iraq',
  SA: 'Saudi Arabia',
  EG: 'Egypt',
  ZA: 'South Africa',
  ZW: 'Zimbabwe',
  BW: 'Botswana',
  NA: 'Namibia',
  MZ: 'Mozambique',
  LS: 'Lesotho',
  SZ: 'Eswatini',
  KE: 'Kenya',
  TZ: 'Tanzania',
  UG: 'Uganda',
  RW: 'Rwanda',
  BI: 'Burundi'
};
